-- Create the database  
-- CREATE DATABASE cafeteria_DB
-- GO
--DROP DATABASE cafeteriaDB;

-- Use the created database  
USE cafeteria_DB
GO
--USE MASTER;

-- Create the CANVA table  
CREATE TABLE CANVA (  
    ID_CANVA VARCHAR(5) PRIMARY KEY,  
    WIDTH FLOAT,  
    HEIGHT FLOAT,
    CREATED_AT DATETIME,
    UPDATE_AT DATETIME
)
GO

-- Create the ADMIN table  
CREATE TABLE ADMIN (  
    ID_ADMIN VARCHAR(5) PRIMARY KEY,  
    EMAIL VARCHAR(255),  
    PASSWORDHASH VARBINARY(64),
    SALT VARBINARY(16),
    CREATED_AT DATETIME,
    UPDATE_AT DATETIME
)
GO
-- ALTER TABLE ADMIN
-- ADD Salt VARBINARY(16);

-- -- Step 1: Add a new PasswordHash column with the VARBINARY type
-- ALTER TABLE ADMIN
-- ADD PasswordHash VARBINARY(64);

-- -- Step 2: Copy data from the old PASSWORD column if needed
-- -- This step is only if you still need the old data in some way.
-- -- Ideally, rehash the passwords before inserting into PasswordHash.
-- UPDATE ADMIN
-- SET PasswordHash = CONVERT(VARBINARY(64), PASSWORD);

-- -- Step 3: Drop the old PASSWORD column
-- ALTER TABLE ADMIN
-- DROP COLUMN PASSWORD;

-- Create the CANVA_ADMIN table  
CREATE TABLE CANVA_ADMIN (  
    ID_CANVA VARCHAR(5),  
    ID_ADMIN VARCHAR(5),
    LOGIN_STATUS VARCHAR(50),  
    PRIMARY KEY (ID_CANVA, ID_ADMIN),  
    FOREIGN KEY (ID_CANVA) REFERENCES CANVA(ID_CANVA),  
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMIN(ID_ADMIN),
    CREATED_AT DATETIME,
    UPDATE_AT DATETIME
)
GO

-- Create the SHAPE_TYPE table  
CREATE TABLE SHAPE_TYPE (  
    ID_SHAPE VARCHAR(5) PRIMARY KEY,
    WIDTH FLOAT,  
    HEIGHT FLOAT,
    RADIUS FLOAT,
    SHAPE_TYPENAME VARCHAR(50), 
    CREATED_AT DATETIME,
    UPDATE_AT DATETIME
)
GO

-- Create the CAFETERIA_TABLE table  
CREATE TABLE CAFETERIA_TABLE (  
    ID_TABLE VARCHAR(5) PRIMARY KEY,
    X_COORDINATE FLOAT,
    Y_COORDINATE FLOAT,
    ID_SHAPE VARCHAR(5),  
    ID_CANVA VARCHAR(5),
    ID_ADMIN VARCHAR(5),
    TABLE_STATUS VARCHAR(50),
    CREATED_AT DATETIME,
    UPDATE_AT DATETIME,
    FOREIGN KEY (ID_SHAPE) REFERENCES SHAPE_TYPE(ID_SHAPE),
    FOREIGN KEY (ID_CANVA, ID_ADMIN) REFERENCES CANVA_ADMIN(ID_CANVA, ID_ADMIN)
)
GO

-- ALTER TABLE CAFETERIA_TABLE
-- ADD X_COORDINATE FLOAT;
-- ALTER TABLE CAFETERIA_TABLE
-- ADD Y_COORDINATE FLOAT;


-- UPDATE CAFETERIA_TABLE
-- SET X_COORDINATE = MIDPOINT_X_COORDINATE;

-- UPDATE CAFETERIA_TABLE
-- SET Y_COORDINATE = MIDPOINT_Y_COORDINATE;

-- -- Step 3: Drop the old COLLUMN column
-- ALTER TABLE CAFETERIA_TABLE
-- DROP COLUMN MIDPOINT_X_COORDINATE;

-- ALTER TABLE CAFETERIA_TABLE
-- DROP COLUMN MIDPOINT_Y_COORDINATE;

-- ALTER TABLE CAFETERIA_TABLE
-- ADD MIDPOINT_X_COORDINATE FLOAT
-- GO

-- ALTER TABLE CAFETERIA_TABLE
-- ADD MIDPOINT_Y_COORDINATE FLOAT
-- GO

-- UPDATE CAFETERIA_TABLE
-- SET MIDPOINT_X_COORDINATE = ST.MIDPOINT_X_COORDINATE, 
--     MIDPOINT_Y_COORDINATE = ST.MIDPOINT_Y_COORDINATE
-- FROM CAFETERIA_TABLE CT
-- INNER JOIN SHAPE_TYPE ST ON CT.ID_SHAPE = ST.ID_SHAPE

-- SELECT *
-- FROM CAFETERIA_TABLE

-- ALTER TABLE SHAPE_TYPE
-- DROP COLUMN MIDPOINT_X_COORDINATE;

-- ALTER TABLE SHAPE_TYPE
-- DROP COLUMN MIDPOINT_Y_COORDINATE;

-- SELECT *
-- FROM SHAPE_TYPE

-- Create the FOOD_TYPE table  
CREATE TABLE FOOD_TYPE (  
    ID_FOOD VARCHAR(5) PRIMARY KEY,
    FOOD_NAME VARCHAR(255),
    FOOD_TYPENAME VARCHAR(255),
    AMOUNT_LEFT INT,
    PRICE DECIMAL(10, 2),  
    FOOD_TYPE_STATUS VARCHAR(50),
    IMAGE_LINK VARCHAR(255),
    CREATED_AT DATETIME,
    UPDATE_AT DATETIME
)
GO

-- ALTER TABLE FOOD_TYPE
-- ADD IMAGE_LINK VARCHAR(255)
-- GO

-- ALTER TABLE FOOD_TYPE
-- ADD FOOD_TYPENAME VARCHAR(255)
-- GO


-- Create the FOOD_TABLE table  
CREATE TABLE FOOD_TABLE (  
    ID_FOOD VARCHAR(5),
    ID_TABLE VARCHAR(5),  
    AMOUNT_IN_TABLE INT,
    PRIMARY KEY (ID_FOOD, ID_TABLE),
    FOREIGN KEY (ID_FOOD) REFERENCES FOOD_TYPE(ID_FOOD),
    FOREIGN KEY (ID_TABLE) REFERENCES CAFETERIA_TABLE(ID_TABLE),
    CREATED_AT DATETIME,
    UPDATE_AT DATETIME
);

-- ALTER TABLE FOOD_TABLE
-- DROP CONSTRAINT PK__FOOD_TAB__61DE7B381A96C003;

-- ALTER TABLE FOOD_TABLE
-- ADD CONSTRAINT FOOD_TABLE_PK PRIMARY KEY (ID_TABLE, ID_FOOD);

-- SELECT 
--     tc.CONSTRAINT_NAME, 
--     tc.TABLE_NAME, 
--     kcu.COLUMN_NAME
-- FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS tc
-- JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu 
--     ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
-- WHERE tc.TABLE_NAME = 'FOOD_TABLE' AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY';

-- ALTER TABLE FOOD_TABLE
-- ALTER COLUMN ID_TABLE varchar(5) NOT NULL;
