-- use cafeteria_DB
-- go

use cafeteriaDB
go

create or alter view V_ADMIN_INFOR
as
	select ID_ADMIN, EMAIL
	from ADMIN
	where EMAIL = CURRENT_USER
go

create or alter view V_ADMIN_UPDATE_DELETE_INFOR
as
	select EMAIL, PASSWORDHASH
	from ADMIN
	where EMAIL = CURRENT_USER
go

create or alter view V_ADMIN_TABLE
as
	select ID_TABLE, ID_SHAPE, TABLE_STATUS, X_COORDINATE, Y_COORDINATE
	from CAFETERIA_TABLE
go

create or alter view V_ADMIN_CANVA_ADMIN
as
	select CA.LOGIN_STATUS
	from CANVA_ADMIN CA, ADMIN AD
    where AD.EMAIL = CURRENT_USER
        AND AD.ID_ADMIN = CA.ID_ADMIN
go

create or alter view V_ADMIN_FOOD_TABLE
as
	select *
	from FOOD_TABLE
go

create or alter view V_ADMIN_TABLEInCANVA
as
	SELECT CT.X_COORDINATE, CT.Y_COORDINATE, ST.WIDTH, ST.HEIGHT, ST.RADIUS,
        CT.TABLE_STATUS, CT.ID_TABLE, CT.ID_SHAPE, CT.ID_CANVA
    FROM CAFETERIA_TABLE CT, SHAPE_TYPE ST
	WHERE CT.ID_SHAPE = ST.ID_SHAPE
go

create or alter view V_ADMIN_FOODsOnTABLE
as
	SELECT FTY.ID_FOOD, FTA.ID_TABLE, FTY.FOOD_NAME, FTY.AMOUNT_LEFT,
		FTY.PRICE, FTY.FOOD_TYPE_STATUS, FTY.IMAGE_LINK,
		FTA.AMOUNT_IN_TABLE
    FROM FOOD_TABLE FTA, FOOD_TYPE FTY
	WHERE FTA.ID_FOOD = FTY.ID_FOOD
go

GRANT SELECT, INSERT, UPDATE, DELETE ON SHAPE_TYPE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON FOOD_TYPE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_TABLE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON CANVA TO ADMIN

GRANT SELECT ON V_ADMIN_INFOR TO ADMIN

GRANT SELECT, UPDATE, DELETE ON V_ADMIN_UPDATE_DELETE_INFOR TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_CANVA_ADMIN TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_FOOD_TABLE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_FOODsOnTABLE TO ADMIN

GRANT SELECT, INSERT, UPDATE, DELETE ON V_ADMIN_TABLEInCANVA TO ADMIN

GO