//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD_TYPE
    {
        public string ID_FOOD { get; set; }
        public string FOOD_NAME { get; set; }
        public string FOOD_TYPENAME { get; set; }
        public Nullable<int> AMOUNT_LEFT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string FOOD_TYPE_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public string IMAGE_LINK { get; set; }
    
        public virtual FOOD_TABLE FOOD_TABLE { get; set; }
    }
}
