//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafeteriaDBEntities : DbContext
    {
        public cafeteriaDBEntities()
            : base("name=cafeteriaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CAFETERIA_TABLE> CAFETERIA_TABLE { get; set; }
        public virtual DbSet<CANVA> CANVAs { get; set; }
        public virtual DbSet<CANVA_ADMIN> CANVA_ADMIN { get; set; }
        public virtual DbSet<FOOD_TYPE> FOOD_TYPE { get; set; }
        public virtual DbSet<SHAPE_TYPE> SHAPE_TYPE { get; set; }
        public virtual DbSet<FOOD_TABLE> FOOD_TABLE { get; set; }
        public virtual DbSet<V_ADMIN_FOOD_TABLE> V_ADMIN_FOOD_TABLE { get; set; }
        public virtual DbSet<V_ADMIN_INFOR> V_ADMIN_INFOR { get; set; }
        public virtual DbSet<V_ADMIN_TABLE> V_ADMIN_TABLE { get; set; }
        public virtual DbSet<V_ADMIN_TABLE_FOODs> V_ADMIN_TABLE_FOODs { get; set; }
    }
}
