//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ADMIN_TABLE_FOODs
    {
        public Nullable<double> X_COORDINATE { get; set; }
        public Nullable<double> Y_COORDINATE { get; set; }
        public Nullable<double> WIDTH { get; set; }
        public Nullable<double> HEIGHT { get; set; }
        public Nullable<double> RADIUS { get; set; }
        public string ID_FOOD { get; set; }
        public string FOOD_NAME { get; set; }
        public string FOOD_TYPENAME { get; set; }
        public Nullable<int> AMOUNT_IN_TABLE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string FOOD_TYPE_STATUS { get; set; }
        public string IMAGE_LINK { get; set; }
        public string TABLE_STATUS { get; set; }
        public string ID_TABLE { get; set; }
        public string SHAPE_TYPENAME { get; set; }
        public string ID_CANVA { get; set; }
    }
}
