//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafeteria_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHAPE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHAPE_TYPE()
        {
            this.CAFETERIA_TABLE = new HashSet<CAFETERIA_TABLE>();
        }
    
        public string ID_SHAPE { get; set; }
        public Nullable<double> WIDTH { get; set; }
        public Nullable<double> HEIGHT { get; set; }
        public Nullable<double> RADIUS { get; set; }
        public string SHAPE_TYPENAME { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAFETERIA_TABLE> CAFETERIA_TABLE { get; set; }
    }
}
