//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafeteria_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ADMIN_FOOD_TABLE
    {
        public string ID_FOOD { get; set; }
        public string ID_TABLE { get; set; }
        public Nullable<int> AMOUNT_IN_TABLE { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
    }
}
