//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafeteria_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ADMIN_TABLE
    {
        public string ID_TABLE { get; set; }
        public string ID_SHAPE { get; set; }
        public string TABLE_STATUS { get; set; }
        public Nullable<double> X_COORDINATE { get; set; }
        public Nullable<double> Y_COORDINATE { get; set; }
    }
}
