//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeteriaDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cafeteriaDBEntities1 : DbContext
    {
        public cafeteriaDBEntities1()
            : base("name=cafeteriaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CAFETERIA_TABLE> CAFETERIA_TABLE { get; set; }
        public virtual DbSet<CANVA> CANVAs { get; set; }
        public virtual DbSet<CANVA_ADMIN> CANVA_ADMIN { get; set; }
        public virtual DbSet<FOOD_TABLE> FOOD_TABLE { get; set; }
        public virtual DbSet<FOOD_TYPE> FOOD_TYPE { get; set; }
        public virtual DbSet<SHAPE_TYPE> SHAPE_TYPE { get; set; }
    
        public virtual ObjectResult<V_ADMIN_FOODsOnTABLE> sp_ADMIN_FOODsOnTABLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<V_ADMIN_FOODsOnTABLE>("sp_ADMIN_FOODsOnTABLE");
        }
    
        public virtual ObjectResult<V_ADMIN_TABLEInCANVA> sp_ADMIN_TABLEInCANVA(string iD_CANVA)
        {
            var iD_CANVAParameter = iD_CANVA != null ?
                new ObjectParameter("ID_CANVA", iD_CANVA) :
                new ObjectParameter("ID_CANVA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<V_ADMIN_TABLEInCANVA>("sp_ADMIN_TABLEInCANVA", iD_CANVAParameter);
        }
    }
}
