//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriaDBLocalHost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafeteriaDBEntities1 : DbContext
    {
        public cafeteriaDBEntities1()
            : base("name=cafeteriaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CAFETERIA_TABLE> CAFETERIA_TABLE { get; set; }
        public virtual DbSet<CANVA> CANVAs { get; set; }
        public virtual DbSet<CANVA_ADMIN> CANVA_ADMIN { get; set; }
        public virtual DbSet<FOOD_TYPE> FOOD_TYPE { get; set; }
        public virtual DbSet<SHAPE_TYPE> SHAPE_TYPE { get; set; }
        public virtual DbSet<FOOD_TABLE> FOOD_TABLE { get; set; }
        public virtual DbSet<V_ADMIN_FOODsOnTABLE> V_ADMIN_FOODsOnTABLE { get; set; }
        public virtual DbSet<V_ADMIN_TABLEInCANVA> V_ADMIN_TABLEInCANVA { get; set; }
    }
}
