//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriaDBLocalHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANVA()
        {
            this.CANVA_ADMIN = new HashSet<CANVA_ADMIN>();
        }
    
        public string ID_CANVA { get; set; }
        public Nullable<double> WIDTH { get; set; }
        public Nullable<double> HEIGHT { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANVA_ADMIN> CANVA_ADMIN { get; set; }
    }
}
