//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriaDBLocalHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ADMIN_FOODsOnTABLE
    {
        public string ID_FOOD { get; set; }
        public string ID_TABLE { get; set; }
        public string FOOD_NAME { get; set; }
        public Nullable<int> AMOUNT_LEFT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string FOOD_TYPE_STATUS { get; set; }
        public string IMAGE_LINK { get; set; }
        public Nullable<int> AMOUNT_IN_TABLE { get; set; }
    }
}
