//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityCafeteriaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRoleMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRoleMenu()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int Id { get; set; }
        public string RoleId { get; set; }
        public int MenuId { get; set; }
    
        public virtual AspNetMenu AspNetMenu { get; set; }
        public virtual AspNetMenu AspNetMenu1 { get; set; }
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetRole AspNetRole1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
