//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityCafeteriaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TakePermission_From_UserAndApiAndRole
    {
        public string Permission { get; set; }
        public string UserName { get; set; }
        public string API { get; set; }
        public string RoleName { get; set; }
    }
}
